# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'service'

require 'grpc'
require 'user_pb'

module Service
  module User
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'service.User'

      rpc :Create, UserCreateRequest, UserCreateResponse
    end

    Stub = Service.rpc_stub_class
  end
end
