// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package service

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *UserCreateRequest) Validate() error {
	if !(this.Age > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be greater than '-1'`, this.Age))
	}
	if !(this.Age < 151) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be less than '151'`, this.Age))
	}
	return nil
}
func (this *UserCreateResponse) Validate() error {
	return nil
}
